name: my_flutter_web_app
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.5.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.1.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/