// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDErNvlMfJIdGNkKm675kKlRGg3Fo4_g-w',
    appId: '1:1058801480700:web:e01f78588e3c7d46fcf879',
    messagingSenderId: '1058801480700',
    projectId: 'electrack-f1425',
    authDomain: 'electrack-f1425.firebaseapp.com',
    storageBucket: 'electrack-f1425.firebasestorage.app',
    measurementId: 'G-67FRC9JTNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqXXQQlyfYxWCuGaVX5lSbPM77vXHqbk',
    appId: '1:1058801480700:android:cf7ff23f68dfcf65fcf879',
    messagingSenderId: '1058801480700',
    projectId: 'electrack-f1425',
    storageBucket: 'electrack-f1425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZ3eKEBMX7eGzB6qJ1SA2FdrfJ4_PvDQ',
    appId: '1:1058801480700:ios:5ff3c29ae1dcf81bfcf879',
    messagingSenderId: '1058801480700',
    projectId: 'electrack-f1425',
    storageBucket: 'electrack-f1425.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZ3eKEBMX7eGzB6qJ1SA2FdrfJ4_PvDQ',
    appId: '1:1058801480700:ios:5ff3c29ae1dcf81bfcf879',
    messagingSenderId: '1058801480700',
    projectId: 'electrack-f1425',
    storageBucket: 'electrack-f1425.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDErNvlMfJIdGNkKm675kKlRGg3Fo4_g-w',
    appId: '1:1058801480700:web:89aee84843370434fcf879',
    messagingSenderId: '1058801480700',
    projectId: 'electrack-f1425',
    authDomain: 'electrack-f1425.firebaseapp.com',
    storageBucket: 'electrack-f1425.firebasestorage.app',
    measurementId: 'G-YY7Y55WM34',
  );
}
